version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: "mysqladmin ping"
      interval: 10s
      timeout: 5s
      retries: 5
